/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea2;

/**
 *
 * @author marcelino
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIntro = new javax.swing.JLabel();
        cboTabla = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio3");

        lblIntro.setText("Seleccione Tabla: ");

        cboTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cboTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTablaActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cboTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntro)
                    .addComponent(cboTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTablaActionPerformed
        // TODO add your handling code here:
        if(cboTabla.getSelectedIndex() == 0){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 1 * i;
                    txtResultado.setText(txtResultado.getText() + 1 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 1){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 2 * i;
                    txtResultado.setText(txtResultado.getText() + 2 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 2){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 3 * i;
                    txtResultado.setText(txtResultado.getText() + 3 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 3){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 4 * i;
                    txtResultado.setText(txtResultado.getText() + 4 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 4){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 5 * i;
                    txtResultado.setText(txtResultado.getText() + 5 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 5){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 6 * i;
                    txtResultado.setText(txtResultado.getText() + 6 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 6){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 7 * i;
                    txtResultado.setText(txtResultado.getText() + 7 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 7){ 
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 8 * i;
                    txtResultado.setText(txtResultado.getText() + 8 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 8){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 9 * i;
                    txtResultado.setText(txtResultado.getText() + 9 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
        
        if(cboTabla.getSelectedIndex() == 9){
                txtResultado.setText("");
                int multiplicacion = 0;
                for (int i = 1; i <= 10; i++) {
                    multiplicacion = 10 * i;
                    txtResultado.setText(txtResultado.getText() + 10 + " X " + i + " = " + multiplicacion +"\n");
                }
        }
    }//GEN-LAST:event_cboTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntro;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
